### ISSUE TITLE
add key listeners

### ISSUE THREAD

**Issue by mlyght** [moreta/vue-search-select#17]
use of keyboard shortcut keys to select, or scroll down

**Comment by moreta** [comment]
❓

**Comment by samuelcolvin** [comment]
This would be extremely useful, without it the demo is very frustrating to use for those of us used to select2 or standard select. Particularly on laptop where people use arrow keys more.

**Comment by vesper8** [comment]
+1 I have integrated your package in my app and it's very handy and easy to use.. but not being able to use up/down on the keyboard really makes it much less appealing.. what is involved in getting this to work? is it that difficult?

**Comment by vesper8** [comment]
Actually I'm confused.. this looks like it should already be working? There's this code in the BasicSelect.vue component

@moreta how come this code doesn't work?

```
 <input class="search" autocomplete="off" tabindex="0" v-model="searchText" ref="searchInput"
           @blur="blurInput"
           @keydown.up="prevItem"
           @keydown.down="nextItem"
           @keyup.enter="enterItem"
           @keydown.delete="deleteTextOrItem"
    />
```

**Comment by vags15** [comment]
A very good evening friend @moreta , I want to thank you in advance for sharing vue-search-select, it is super easy to use and above all very beautiful at the time of search, but it would be possible to implement the key enter and the activation of the up and down navigation keys.

**Comment by moreta** [comment]
Thank all 
I've add this feature at v2.3.7

**Comment by vesper8** [comment]
hrm, first of all thanks for tackling the issue.

I've installed the newest 2.3.7 and indeed I can now navigate up and down using the arrow keys, and make a selection using enter. However there is some weird behavior.

First of all, when I use TAB to switch from a form text field to a vue-search-select field it doesn't trigger the list to be shown. If I press enter is auto-selects the first item but doesn't show the list.

One way to show the list is to press delete/backspace. But could we have it so that the list is shown on focus ?

Another issue is with list containing many items (50+ items), when you start to press down down down to go through the list items, at first it's ok, but then it starts to paginate down but it paginates too far and after 2 page-downs (from pressing down arrow repeatedly) it becomes out of sync with the cursor (highlighted item) and you no longer see which item you are on

**Comment by moreta** [comment]
@vesper8 
Thank you for your feedback.

> First of all, when I use TAB to switch from a form text field to a vue-search-select field it doesn't trigger the list to be shown. If I press enter is auto-selects the first item but doesn't show the list.

I'll fix this.

> but then it starts to paginate down but it paginates too far and after 2 page-downs (from pressing down arrow repeatedly) it becomes out of sync with the cursor (highlighted item) and you no longer see which item you are on

hmm, I can't reproduce this on demo page.
(I add more item 50+ but pagination is ok)

I added mouseover event. when mouseover item, item selected.
Your review not related to this mouseover event?
